// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recipe.proto

package recipe

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 工廠列舉。 TODO: move to shared library.
type FactoryID int32

const (
	FactoryID_UNASSIGNED FactoryID = 0
	FactoryID_KY         FactoryID = 1
	FactoryID_KU         FactoryID = 2
	FactoryID_KS         FactoryID = 3
	FactoryID_KC         FactoryID = 4
	FactoryID_KT         FactoryID = 5
	FactoryID_KV         FactoryID = 6
	FactoryID_KV2        FactoryID = 7
	FactoryID_KI         FactoryID = 8
)

var FactoryID_name = map[int32]string{
	0: "UNASSIGNED",
	1: "KY",
	2: "KU",
	3: "KS",
	4: "KC",
	5: "KT",
	6: "KV",
	7: "KV2",
	8: "KI",
}
var FactoryID_value = map[string]int32{
	"UNASSIGNED": 0,
	"KY":         1,
	"KU":         2,
	"KS":         3,
	"KC":         4,
	"KT":         5,
	"KV":         6,
	"KV2":        7,
	"KI":         8,
}

func (x FactoryID) String() string {
	return proto.EnumName(FactoryID_name, int32(x))
}
func (FactoryID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_recipe_0a215f2e05af0fe8, []int{0}
}

type Version_Status int32

const (
	Version_UNASSIGNED   Version_Status = 0
	Version_TEMPORARY    Version_Status = 1
	Version_EXPERIMENTAL Version_Status = 2
	Version_TEST         Version_Status = 3
	Version_PRODUCTION   Version_Status = 4
	Version_DEPRECATED   Version_Status = 5
)

var Version_Status_name = map[int32]string{
	0: "UNASSIGNED",
	1: "TEMPORARY",
	2: "EXPERIMENTAL",
	3: "TEST",
	4: "PRODUCTION",
	5: "DEPRECATED",
}
var Version_Status_value = map[string]int32{
	"UNASSIGNED":   0,
	"TEMPORARY":    1,
	"EXPERIMENTAL": 2,
	"TEST":         3,
	"PRODUCTION":   4,
	"DEPRECATED":   5,
}

func (x Version_Status) String() string {
	return proto.EnumName(Version_Status_name, int32(x))
}
func (Version_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_recipe_0a215f2e05af0fe8, []int{3, 0}
}

type Process_Config_Step_Setting_Type int32

const (
	Process_Config_Step_Setting_UNASSIGNED    Process_Config_Step_Setting_Type = 0
	Process_Config_Step_Setting_CONTROL_VALUE Process_Config_Step_Setting_Type = 100
	Process_Config_Step_Setting_CONTROL_RANGE Process_Config_Step_Setting_Type = 101
	Process_Config_Step_Setting_CONTROL_MODE  Process_Config_Step_Setting_Type = 102
	// 非控制之檢驗量測標準。
	Process_Config_Step_Setting_MEASUREMENT_VALUE Process_Config_Step_Setting_Type = 200
	Process_Config_Step_Setting_MEASUREMENT_MAX   Process_Config_Step_Setting_Type = 201
	Process_Config_Step_Setting_MEASUREMENT_MIN   Process_Config_Step_Setting_Type = 202
	Process_Config_Step_Setting_MEASUREMENT_RANGE Process_Config_Step_Setting_Type = 203
	Process_Config_Step_Setting_MEASUREMENT_MODE  Process_Config_Step_Setting_Type = 204
)

var Process_Config_Step_Setting_Type_name = map[int32]string{
	0:   "UNASSIGNED",
	100: "CONTROL_VALUE",
	101: "CONTROL_RANGE",
	102: "CONTROL_MODE",
	200: "MEASUREMENT_VALUE",
	201: "MEASUREMENT_MAX",
	202: "MEASUREMENT_MIN",
	203: "MEASUREMENT_RANGE",
	204: "MEASUREMENT_MODE",
}
var Process_Config_Step_Setting_Type_value = map[string]int32{
	"UNASSIGNED":        0,
	"CONTROL_VALUE":     100,
	"CONTROL_RANGE":     101,
	"CONTROL_MODE":      102,
	"MEASUREMENT_VALUE": 200,
	"MEASUREMENT_MAX":   201,
	"MEASUREMENT_MIN":   202,
	"MEASUREMENT_RANGE": 203,
	"MEASUREMENT_MODE":  204,
}

func (x Process_Config_Step_Setting_Type) String() string {
	return proto.EnumName(Process_Config_Step_Setting_Type_name, int32(x))
}
func (Process_Config_Step_Setting_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_recipe_0a215f2e05af0fe8, []int{4, 0, 0, 0, 0}
}

// 數值參數 (value, value+aux) with errorMargin
type Param struct {
	Unit                 string   `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Value                float32  `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	Aux                  float32  `protobuf:"fixed32,3,opt,name=aux,proto3" json:"aux,omitempty"`
	ErrorMargin          float32  `protobuf:"fixed32,4,opt,name=errorMargin,proto3" json:"errorMargin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Param) Reset()         { *m = Param{} }
func (m *Param) String() string { return proto.CompactTextString(m) }
func (*Param) ProtoMessage()    {}
func (*Param) Descriptor() ([]byte, []int) {
	return fileDescriptor_recipe_0a215f2e05af0fe8, []int{0}
}
func (m *Param) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Param.Unmarshal(m, b)
}
func (m *Param) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Param.Marshal(b, m, deterministic)
}
func (dst *Param) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Param.Merge(dst, src)
}
func (m *Param) XXX_Size() int {
	return xxx_messageInfo_Param.Size(m)
}
func (m *Param) XXX_DiscardUnknown() {
	xxx_messageInfo_Param.DiscardUnknown(m)
}

var xxx_messageInfo_Param proto.InternalMessageInfo

func (m *Param) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Param) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Param) GetAux() float32 {
	if m != nil {
		return m.Aux
	}
	return 0
}

func (m *Param) GetErrorMargin() float32 {
	if m != nil {
		return m.ErrorMargin
	}
	return 0
}

// 原材料。
type Material struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Param                *Param   `protobuf:"bytes,3,opt,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Material) Reset()         { *m = Material{} }
func (m *Material) String() string { return proto.CompactTextString(m) }
func (*Material) ProtoMessage()    {}
func (*Material) Descriptor() ([]byte, []int) {
	return fileDescriptor_recipe_0a215f2e05af0fe8, []int{1}
}
func (m *Material) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Material.Unmarshal(m, b)
}
func (m *Material) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Material.Marshal(b, m, deterministic)
}
func (dst *Material) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Material.Merge(dst, src)
}
func (m *Material) XXX_Size() int {
	return xxx_messageInfo_Material.Size(m)
}
func (m *Material) XXX_DiscardUnknown() {
	xxx_messageInfo_Material.DiscardUnknown(m)
}

var xxx_messageInfo_Material proto.InternalMessageInfo

func (m *Material) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Material) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Material) GetParam() *Param {
	if m != nil {
		return m.Param
	}
	return nil
}

//  工器具、載具。
type Tool struct {
	Role                 string   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tool) Reset()         { *m = Tool{} }
func (m *Tool) String() string { return proto.CompactTextString(m) }
func (*Tool) ProtoMessage()    {}
func (*Tool) Descriptor() ([]byte, []int) {
	return fileDescriptor_recipe_0a215f2e05af0fe8, []int{2}
}
func (m *Tool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tool.Unmarshal(m, b)
}
func (m *Tool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tool.Marshal(b, m, deterministic)
}
func (dst *Tool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tool.Merge(dst, src)
}
func (m *Tool) XXX_Size() int {
	return xxx_messageInfo_Tool.Size(m)
}
func (m *Tool) XXX_DiscardUnknown() {
	xxx_messageInfo_Tool.DiscardUnknown(m)
}

var xxx_messageInfo_Tool proto.InternalMessageInfo

func (m *Tool) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Tool) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// 配方版本。
type Version struct {
	Status               Version_Status `protobuf:"varint,1,opt,name=status,proto3,enum=recipe.Version_Status" json:"status,omitempty"`
	Major                string         `protobuf:"bytes,2,opt,name=major,proto3" json:"major,omitempty"`
	Minor                string         `protobuf:"bytes,3,opt,name=minor,proto3" json:"minor,omitempty"`
	UpdatedAt            int64          `protobuf:"varint,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	UpdatedBy            string         `protobuf:"bytes,5,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	Note                 string         `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_recipe_0a215f2e05af0fe8, []int{3}
}
func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (dst *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(dst, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetStatus() Version_Status {
	if m != nil {
		return m.Status
	}
	return Version_UNASSIGNED
}

func (m *Version) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *Version) GetMinor() string {
	if m != nil {
		return m.Minor
	}
	return ""
}

func (m *Version) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Version) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *Version) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

// 單一工序的定義。
type Process struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Configs              []*Process_Config `protobuf:"bytes,2,rep,name=configs,proto3" json:"configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_recipe_0a215f2e05af0fe8, []int{4}
}
func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (dst *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(dst, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Process) GetConfigs() []*Process_Config {
	if m != nil {
		return m.Configs
	}
	return nil
}

type Process_Config struct {
	// 符合的機台及工具。
	Stations             []string               `protobuf:"bytes,1,rep,name=stations,proto3" json:"stations,omitempty"`
	Tools                []*Tool                `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	Steps                []*Process_Config_Step `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Process_Config) Reset()         { *m = Process_Config{} }
func (m *Process_Config) String() string { return proto.CompactTextString(m) }
func (*Process_Config) ProtoMessage()    {}
func (*Process_Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_recipe_0a215f2e05af0fe8, []int{4, 0}
}
func (m *Process_Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process_Config.Unmarshal(m, b)
}
func (m *Process_Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process_Config.Marshal(b, m, deterministic)
}
func (dst *Process_Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process_Config.Merge(dst, src)
}
func (m *Process_Config) XXX_Size() int {
	return xxx_messageInfo_Process_Config.Size(m)
}
func (m *Process_Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Process_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Process_Config proto.InternalMessageInfo

func (m *Process_Config) GetStations() []string {
	if m != nil {
		return m.Stations
	}
	return nil
}

func (m *Process_Config) GetTools() []*Tool {
	if m != nil {
		return m.Tools
	}
	return nil
}

func (m *Process_Config) GetSteps() []*Process_Config_Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

// 分階段的材料及控制、檢驗設定。
type Process_Config_Step struct {
	Materials            []*Material                    `protobuf:"bytes,1,rep,name=materials,proto3" json:"materials,omitempty"`
	Settings             []*Process_Config_Step_Setting `protobuf:"bytes,2,rep,name=settings,proto3" json:"settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Process_Config_Step) Reset()         { *m = Process_Config_Step{} }
func (m *Process_Config_Step) String() string { return proto.CompactTextString(m) }
func (*Process_Config_Step) ProtoMessage()    {}
func (*Process_Config_Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_recipe_0a215f2e05af0fe8, []int{4, 0, 0}
}
func (m *Process_Config_Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process_Config_Step.Unmarshal(m, b)
}
func (m *Process_Config_Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process_Config_Step.Marshal(b, m, deterministic)
}
func (dst *Process_Config_Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process_Config_Step.Merge(dst, src)
}
func (m *Process_Config_Step) XXX_Size() int {
	return xxx_messageInfo_Process_Config_Step.Size(m)
}
func (m *Process_Config_Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Process_Config_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Process_Config_Step proto.InternalMessageInfo

func (m *Process_Config_Step) GetMaterials() []*Material {
	if m != nil {
		return m.Materials
	}
	return nil
}

func (m *Process_Config_Step) GetSettings() []*Process_Config_Step_Setting {
	if m != nil {
		return m.Settings
	}
	return nil
}

type Process_Config_Step_Setting struct {
	Name                 string                           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 Process_Config_Step_Setting_Type `protobuf:"varint,1,opt,name=type,proto3,enum=recipe.Process_Config_Step_Setting_Type" json:"type,omitempty"`
	Param                *Param                           `protobuf:"bytes,3,opt,name=param,proto3" json:"param,omitempty"`
	Mode                 string                           `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *Process_Config_Step_Setting) Reset()         { *m = Process_Config_Step_Setting{} }
func (m *Process_Config_Step_Setting) String() string { return proto.CompactTextString(m) }
func (*Process_Config_Step_Setting) ProtoMessage()    {}
func (*Process_Config_Step_Setting) Descriptor() ([]byte, []int) {
	return fileDescriptor_recipe_0a215f2e05af0fe8, []int{4, 0, 0, 0}
}
func (m *Process_Config_Step_Setting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process_Config_Step_Setting.Unmarshal(m, b)
}
func (m *Process_Config_Step_Setting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process_Config_Step_Setting.Marshal(b, m, deterministic)
}
func (dst *Process_Config_Step_Setting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process_Config_Step_Setting.Merge(dst, src)
}
func (m *Process_Config_Step_Setting) XXX_Size() int {
	return xxx_messageInfo_Process_Config_Step_Setting.Size(m)
}
func (m *Process_Config_Step_Setting) XXX_DiscardUnknown() {
	xxx_messageInfo_Process_Config_Step_Setting.DiscardUnknown(m)
}

var xxx_messageInfo_Process_Config_Step_Setting proto.InternalMessageInfo

func (m *Process_Config_Step_Setting) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Process_Config_Step_Setting) GetType() Process_Config_Step_Setting_Type {
	if m != nil {
		return m.Type
	}
	return Process_Config_Step_Setting_UNASSIGNED
}

func (m *Process_Config_Step_Setting) GetParam() *Param {
	if m != nil {
		return m.Param
	}
	return nil
}

func (m *Process_Config_Step_Setting) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

// 配合表: 多個單一工序及異常處理流程。
type Recipe struct {
	Id             string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductID      string     `protobuf:"bytes,2,opt,name=productID,proto3" json:"productID,omitempty"`
	Factory        FactoryID  `protobuf:"varint,3,opt,name=factory,proto3,enum=recipe.FactoryID" json:"factory,omitempty"`
	VersionHistory []*Version `protobuf:"bytes,4,rep,name=versionHistory,proto3" json:"versionHistory,omitempty"`
	// 來源配方。
	SpecID string `protobuf:"bytes,5,opt,name=specID,proto3" json:"specID,omitempty"`
	// 配合的工序。e.g., 素煉、加促、…
	Processes            []*Process             `protobuf:"bytes,6,rep,name=processes,proto3" json:"processes,omitempty"`
	OptionalFlows        []*Recipe_OptionalFlow `protobuf:"bytes,9,rep,name=optionalFlows,proto3" json:"optionalFlows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Recipe) Reset()         { *m = Recipe{} }
func (m *Recipe) String() string { return proto.CompactTextString(m) }
func (*Recipe) ProtoMessage()    {}
func (*Recipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_recipe_0a215f2e05af0fe8, []int{5}
}
func (m *Recipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recipe.Unmarshal(m, b)
}
func (m *Recipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recipe.Marshal(b, m, deterministic)
}
func (dst *Recipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recipe.Merge(dst, src)
}
func (m *Recipe) XXX_Size() int {
	return xxx_messageInfo_Recipe.Size(m)
}
func (m *Recipe) XXX_DiscardUnknown() {
	xxx_messageInfo_Recipe.DiscardUnknown(m)
}

var xxx_messageInfo_Recipe proto.InternalMessageInfo

func (m *Recipe) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Recipe) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *Recipe) GetFactory() FactoryID {
	if m != nil {
		return m.Factory
	}
	return FactoryID_UNASSIGNED
}

func (m *Recipe) GetVersionHistory() []*Version {
	if m != nil {
		return m.VersionHistory
	}
	return nil
}

func (m *Recipe) GetSpecID() string {
	if m != nil {
		return m.SpecID
	}
	return ""
}

func (m *Recipe) GetProcesses() []*Process {
	if m != nil {
		return m.Processes
	}
	return nil
}

func (m *Recipe) GetOptionalFlows() []*Recipe_OptionalFlow {
	if m != nil {
		return m.OptionalFlows
	}
	return nil
}

// 部份檢驗或異常處理流程。
type Recipe_OptionalFlow struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AfterProcessID       int32      `protobuf:"varint,2,opt,name=afterProcessID,proto3" json:"afterProcessID,omitempty"`
	MaxRepetitions       int32      `protobuf:"varint,3,opt,name=maxRepetitions,proto3" json:"maxRepetitions,omitempty"`
	Processes            []*Process `protobuf:"bytes,4,rep,name=processes,proto3" json:"processes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Recipe_OptionalFlow) Reset()         { *m = Recipe_OptionalFlow{} }
func (m *Recipe_OptionalFlow) String() string { return proto.CompactTextString(m) }
func (*Recipe_OptionalFlow) ProtoMessage()    {}
func (*Recipe_OptionalFlow) Descriptor() ([]byte, []int) {
	return fileDescriptor_recipe_0a215f2e05af0fe8, []int{5, 0}
}
func (m *Recipe_OptionalFlow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recipe_OptionalFlow.Unmarshal(m, b)
}
func (m *Recipe_OptionalFlow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recipe_OptionalFlow.Marshal(b, m, deterministic)
}
func (dst *Recipe_OptionalFlow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recipe_OptionalFlow.Merge(dst, src)
}
func (m *Recipe_OptionalFlow) XXX_Size() int {
	return xxx_messageInfo_Recipe_OptionalFlow.Size(m)
}
func (m *Recipe_OptionalFlow) XXX_DiscardUnknown() {
	xxx_messageInfo_Recipe_OptionalFlow.DiscardUnknown(m)
}

var xxx_messageInfo_Recipe_OptionalFlow proto.InternalMessageInfo

func (m *Recipe_OptionalFlow) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Recipe_OptionalFlow) GetAfterProcessID() int32 {
	if m != nil {
		return m.AfterProcessID
	}
	return 0
}

func (m *Recipe_OptionalFlow) GetMaxRepetitions() int32 {
	if m != nil {
		return m.MaxRepetitions
	}
	return 0
}

func (m *Recipe_OptionalFlow) GetProcesses() []*Process {
	if m != nil {
		return m.Processes
	}
	return nil
}

// 配方表。
type Spec struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductID            string      `protobuf:"bytes,2,opt,name=productID,proto3" json:"productID,omitempty"`
	VersionHistory       []*Version  `protobuf:"bytes,3,rep,name=versionHistory,proto3" json:"versionHistory,omitempty"`
	ParentSpecID         string      `protobuf:"bytes,4,opt,name=parentSpecID,proto3" json:"parentSpecID,omitempty"`
	Materials            []*Material `protobuf:"bytes,8,rep,name=materials,proto3" json:"materials,omitempty"`
	Tools                []*Tool     `protobuf:"bytes,9,rep,name=tools,proto3" json:"tools,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Spec) Reset()         { *m = Spec{} }
func (m *Spec) String() string { return proto.CompactTextString(m) }
func (*Spec) ProtoMessage()    {}
func (*Spec) Descriptor() ([]byte, []int) {
	return fileDescriptor_recipe_0a215f2e05af0fe8, []int{6}
}
func (m *Spec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spec.Unmarshal(m, b)
}
func (m *Spec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spec.Marshal(b, m, deterministic)
}
func (dst *Spec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spec.Merge(dst, src)
}
func (m *Spec) XXX_Size() int {
	return xxx_messageInfo_Spec.Size(m)
}
func (m *Spec) XXX_DiscardUnknown() {
	xxx_messageInfo_Spec.DiscardUnknown(m)
}

var xxx_messageInfo_Spec proto.InternalMessageInfo

func (m *Spec) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Spec) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *Spec) GetVersionHistory() []*Version {
	if m != nil {
		return m.VersionHistory
	}
	return nil
}

func (m *Spec) GetParentSpecID() string {
	if m != nil {
		return m.ParentSpecID
	}
	return ""
}

func (m *Spec) GetMaterials() []*Material {
	if m != nil {
		return m.Materials
	}
	return nil
}

func (m *Spec) GetTools() []*Tool {
	if m != nil {
		return m.Tools
	}
	return nil
}

// 匯出資料結構。
type Dump struct {
	Specs                []*Spec   `protobuf:"bytes,1,rep,name=specs,proto3" json:"specs,omitempty"`
	ActiveSpecIDs        []string  `protobuf:"bytes,2,rep,name=activeSpecIDs,proto3" json:"activeSpecIDs,omitempty"`
	Recipes              []*Recipe `protobuf:"bytes,3,rep,name=recipes,proto3" json:"recipes,omitempty"`
	ActiveRecipeIDs      []string  `protobuf:"bytes,4,rep,name=activeRecipeIDs,proto3" json:"activeRecipeIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Dump) Reset()         { *m = Dump{} }
func (m *Dump) String() string { return proto.CompactTextString(m) }
func (*Dump) ProtoMessage()    {}
func (*Dump) Descriptor() ([]byte, []int) {
	return fileDescriptor_recipe_0a215f2e05af0fe8, []int{7}
}
func (m *Dump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dump.Unmarshal(m, b)
}
func (m *Dump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dump.Marshal(b, m, deterministic)
}
func (dst *Dump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dump.Merge(dst, src)
}
func (m *Dump) XXX_Size() int {
	return xxx_messageInfo_Dump.Size(m)
}
func (m *Dump) XXX_DiscardUnknown() {
	xxx_messageInfo_Dump.DiscardUnknown(m)
}

var xxx_messageInfo_Dump proto.InternalMessageInfo

func (m *Dump) GetSpecs() []*Spec {
	if m != nil {
		return m.Specs
	}
	return nil
}

func (m *Dump) GetActiveSpecIDs() []string {
	if m != nil {
		return m.ActiveSpecIDs
	}
	return nil
}

func (m *Dump) GetRecipes() []*Recipe {
	if m != nil {
		return m.Recipes
	}
	return nil
}

func (m *Dump) GetActiveRecipeIDs() []string {
	if m != nil {
		return m.ActiveRecipeIDs
	}
	return nil
}

func init() {
	proto.RegisterType((*Param)(nil), "recipe.Param")
	proto.RegisterType((*Material)(nil), "recipe.Material")
	proto.RegisterType((*Tool)(nil), "recipe.Tool")
	proto.RegisterType((*Version)(nil), "recipe.Version")
	proto.RegisterType((*Process)(nil), "recipe.Process")
	proto.RegisterType((*Process_Config)(nil), "recipe.Process.Config")
	proto.RegisterType((*Process_Config_Step)(nil), "recipe.Process.Config.Step")
	proto.RegisterType((*Process_Config_Step_Setting)(nil), "recipe.Process.Config.Step.Setting")
	proto.RegisterType((*Recipe)(nil), "recipe.Recipe")
	proto.RegisterType((*Recipe_OptionalFlow)(nil), "recipe.Recipe.OptionalFlow")
	proto.RegisterType((*Spec)(nil), "recipe.Spec")
	proto.RegisterType((*Dump)(nil), "recipe.Dump")
	proto.RegisterEnum("recipe.FactoryID", FactoryID_name, FactoryID_value)
	proto.RegisterEnum("recipe.Version_Status", Version_Status_name, Version_Status_value)
	proto.RegisterEnum("recipe.Process_Config_Step_Setting_Type", Process_Config_Step_Setting_Type_name, Process_Config_Step_Setting_Type_value)
}

func init() { proto.RegisterFile("recipe.proto", fileDescriptor_recipe_0a215f2e05af0fe8) }

var fileDescriptor_recipe_0a215f2e05af0fe8 = []byte{
	// 959 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcd, 0x8e, 0xe3, 0x44,
	0x10, 0xc6, 0xbf, 0x89, 0x6b, 0x92, 0x6c, 0x4f, 0x6b, 0x19, 0x59, 0x81, 0xc3, 0xc8, 0x8b, 0x50,
	0xb4, 0x08, 0x0b, 0xc2, 0x81, 0x0b, 0x12, 0x32, 0x89, 0x77, 0x89, 0x76, 0xf2, 0xa3, 0xb6, 0x33,
	0x2c, 0x12, 0x12, 0x32, 0x49, 0xcf, 0xca, 0x28, 0x49, 0x5b, 0x76, 0x67, 0xd8, 0x79, 0x15, 0x6e,
	0x20, 0x5e, 0x84, 0x1b, 0x2c, 0x1c, 0x10, 0x27, 0x5e, 0x80, 0xf7, 0x40, 0xdd, 0x6d, 0x27, 0x71,
	0x66, 0x60, 0x87, 0x93, 0xbb, 0xbe, 0xfa, 0xaa, 0xaa, 0xbb, 0xfe, 0x12, 0x68, 0xe5, 0x74, 0x91,
	0x66, 0xd4, 0xcf, 0x72, 0xc6, 0x19, 0xb6, 0x95, 0xe4, 0x51, 0xb0, 0x66, 0x49, 0x9e, 0xac, 0x31,
	0x06, 0x73, 0xbb, 0x49, 0xb9, 0xab, 0x9d, 0x6b, 0x3d, 0x87, 0xc8, 0x33, 0x7e, 0x08, 0xd6, 0x75,
	0xb2, 0xda, 0x52, 0x57, 0x3f, 0xd7, 0x7a, 0x3a, 0x51, 0x02, 0x46, 0x60, 0x24, 0xdb, 0x97, 0xae,
	0x21, 0x31, 0x71, 0xc4, 0xe7, 0x70, 0x42, 0xf3, 0x9c, 0xe5, 0xe3, 0x24, 0x7f, 0x91, 0x6e, 0x5c,
	0x53, 0x6a, 0x0e, 0x21, 0xef, 0x0b, 0x68, 0x8e, 0x13, 0x4e, 0xf3, 0x34, 0x59, 0x89, 0x48, 0xfc,
	0x26, 0xa3, 0x55, 0x24, 0x71, 0x16, 0xd8, 0x26, 0x59, 0xab, 0x40, 0x0e, 0x91, 0x67, 0xfc, 0x08,
	0xac, 0x4c, 0x5c, 0x4d, 0x46, 0x3a, 0xe9, 0xb7, 0xfd, 0xf2, 0x01, 0xf2, 0xbe, 0x44, 0xe9, 0xbc,
	0xc7, 0x60, 0xc6, 0x8c, 0x49, 0xa7, 0x39, 0x5b, 0xed, 0x9c, 0x8a, 0x33, 0xee, 0x80, 0x9e, 0x2e,
	0x4b, 0x97, 0x7a, 0xba, 0xf4, 0xbe, 0xd7, 0xa1, 0x71, 0x49, 0xf3, 0x22, 0x65, 0x1b, 0xec, 0x83,
	0x5d, 0xf0, 0x84, 0x6f, 0x0b, 0x69, 0xd1, 0xe9, 0x9f, 0x55, 0xde, 0x4b, 0x82, 0x1f, 0x49, 0x2d,
	0x29, 0x59, 0x22, 0x15, 0xeb, 0xe4, 0x5b, 0x96, 0x97, 0xee, 0x94, 0x20, 0xd1, 0x74, 0xc3, 0x72,
	0x79, 0x45, 0x81, 0x0a, 0x01, 0xbf, 0x0d, 0xce, 0x36, 0x5b, 0x26, 0x9c, 0x2e, 0x03, 0x2e, 0x93,
	0x61, 0x90, 0x3d, 0x70, 0xa0, 0xfd, 0xec, 0xc6, 0xb5, 0xa4, 0xdd, 0x1e, 0x90, 0x89, 0x60, 0x9c,
	0xba, 0x76, 0x99, 0x08, 0xc6, 0xa9, 0xb7, 0x00, 0x5b, 0xdd, 0x06, 0x77, 0x00, 0xe6, 0x93, 0x20,
	0x8a, 0x46, 0x4f, 0x27, 0xe1, 0x10, 0xbd, 0x81, 0xdb, 0xe0, 0xc4, 0xe1, 0x78, 0x36, 0x25, 0x01,
	0xf9, 0x12, 0x69, 0x18, 0x41, 0x2b, 0x7c, 0x3e, 0x0b, 0xc9, 0x68, 0x1c, 0x4e, 0xe2, 0xe0, 0x02,
	0xe9, 0xb8, 0x09, 0x66, 0x1c, 0x46, 0x31, 0x32, 0x84, 0xe9, 0x8c, 0x4c, 0x87, 0xf3, 0x41, 0x3c,
	0x9a, 0x4e, 0x90, 0x29, 0xe4, 0x61, 0x38, 0x23, 0xe1, 0x20, 0x88, 0xc3, 0x21, 0xb2, 0xbc, 0x1f,
	0x2d, 0x68, 0xcc, 0x72, 0xb6, 0xa0, 0x45, 0xb1, 0xab, 0x86, 0x76, 0x50, 0x8d, 0x0f, 0xa0, 0xb1,
	0x60, 0x9b, 0xab, 0xf4, 0x45, 0xe1, 0xea, 0xe7, 0x46, 0xef, 0x64, 0x9f, 0xb1, 0xd2, 0xca, 0x1f,
	0x48, 0x35, 0xa9, 0x68, 0xdd, 0x3f, 0x4c, 0xb0, 0x15, 0x86, 0xbb, 0xd0, 0x14, 0x79, 0x4c, 0xd9,
	0x46, 0xe4, 0xdb, 0xe8, 0x39, 0x64, 0x27, 0x63, 0x0f, 0x2c, 0xce, 0xd8, 0xaa, 0x72, 0xdb, 0xaa,
	0xdc, 0x8a, 0xb2, 0x12, 0xa5, 0xc2, 0x1f, 0x82, 0x55, 0x70, 0x9a, 0x15, 0xae, 0x21, 0x39, 0x6f,
	0xdd, 0x1d, 0xda, 0x8f, 0x38, 0xcd, 0x88, 0x62, 0x76, 0xff, 0x34, 0xc0, 0x14, 0x32, 0xf6, 0xc1,
	0x59, 0x97, 0xad, 0xa7, 0x82, 0x9f, 0xf4, 0x51, 0x65, 0x5f, 0xf5, 0x24, 0xd9, 0x53, 0xf0, 0xa7,
	0xd0, 0x2c, 0x28, 0xe7, 0xe9, 0x66, 0xf7, 0xd2, 0x47, 0xff, 0x11, 0xce, 0x8f, 0x14, 0x97, 0xec,
	0x8c, 0xba, 0x7f, 0xe9, 0xd0, 0x28, 0xd1, 0x3b, 0xfb, 0xfa, 0x93, 0x83, 0xfe, 0xef, 0xf4, 0x7b,
	0xf7, 0x70, 0xee, 0xc7, 0x37, 0x19, 0x2d, 0x27, 0xe5, 0x3e, 0x53, 0x21, 0xc2, 0xae, 0xd9, 0x92,
	0xca, 0xe6, 0x73, 0x88, 0x3c, 0x7b, 0x3f, 0x6b, 0x60, 0x0a, 0x3f, 0xb7, 0x9a, 0xe8, 0x14, 0xda,
	0x83, 0xe9, 0x24, 0x26, 0xd3, 0x8b, 0xaf, 0x2f, 0x83, 0x8b, 0x79, 0x88, 0x96, 0x87, 0x10, 0x09,
	0x26, 0x4f, 0x43, 0x24, 0xa6, 0xbe, 0x55, 0x41, 0xe3, 0xe9, 0x30, 0x44, 0x57, 0xf8, 0x0c, 0x4e,
	0xc7, 0x61, 0x10, 0xcd, 0x49, 0x28, 0xda, 0xad, 0xb4, 0xfd, 0x45, 0xc3, 0x0f, 0xe1, 0xc1, 0x21,
	0x3e, 0x0e, 0x9e, 0xa3, 0x5f, 0x6f, 0xa3, 0xa3, 0x09, 0x7a, 0xa5, 0x1d, 0xfb, 0x50, 0xc1, 0x7e,
	0xd3, 0xf0, 0x9b, 0x80, 0x6a, 0x6c, 0x11, 0xf1, 0x77, 0xcd, 0x7b, 0x65, 0x80, 0x4d, 0xe4, 0x7b,
	0xcb, 0xe1, 0xd6, 0xaa, 0xe1, 0x16, 0x63, 0x95, 0xe5, 0x6c, 0xb9, 0x5d, 0xf0, 0xd1, 0xb0, 0x4c,
	0xf7, 0x1e, 0xc0, 0xef, 0x41, 0xe3, 0x2a, 0x59, 0x70, 0x96, 0xdf, 0xc8, 0xbc, 0x75, 0xfa, 0xa7,
	0x55, 0xde, 0x9e, 0x28, 0x78, 0x34, 0x24, 0x15, 0x03, 0x7f, 0x0c, 0x9d, 0x6b, 0xb5, 0x05, 0x3e,
	0x4f, 0x0b, 0x69, 0x63, 0xca, 0x3e, 0x78, 0x70, 0xb4, 0x23, 0xc8, 0x11, 0x0d, 0x9f, 0x81, 0x5d,
	0x64, 0x74, 0x31, 0x1a, 0x96, 0x73, 0x5d, 0x4a, 0xf8, 0x7d, 0x79, 0x37, 0x51, 0x5d, 0x5a, 0xb8,
	0x76, 0xdd, 0x57, 0x59, 0x76, 0xb2, 0x67, 0xe0, 0x00, 0xda, 0x2c, 0x13, 0xc3, 0x91, 0xac, 0x9e,
	0xac, 0xd8, 0x77, 0x85, 0xeb, 0xd4, 0xbb, 0x5e, 0x65, 0xc0, 0x9f, 0x1e, 0x70, 0x48, 0xdd, 0xa2,
	0xfb, 0x83, 0x06, 0xad, 0x43, 0xfd, 0x9d, 0x23, 0xfd, 0x2e, 0x74, 0x92, 0x2b, 0x4e, 0xf3, 0xf2,
	0x0a, 0x65, 0xde, 0x2c, 0x72, 0x84, 0x0a, 0xde, 0x3a, 0x79, 0x49, 0x68, 0x46, 0x79, 0xaa, 0x66,
	0xd8, 0x50, 0xbc, 0x3a, 0x5a, 0x7f, 0xa6, 0xf9, 0xba, 0x67, 0x7a, 0x7f, 0x6b, 0x60, 0x46, 0x19,
	0x5d, 0xfc, 0xcf, 0x52, 0xde, 0xae, 0x8e, 0x71, 0xbf, 0xea, 0x78, 0xd0, 0xca, 0x92, 0x9c, 0x6e,
	0x78, 0xa4, 0x6a, 0xa4, 0x86, 0xa3, 0x86, 0xd5, 0x97, 0x45, 0xf3, 0xf5, 0xcb, 0x62, 0xb7, 0xbc,
	0x9c, 0x7f, 0x5d, 0x5e, 0xde, 0x4f, 0x1a, 0x98, 0xc3, 0xed, 0x3a, 0x13, 0x64, 0xd1, 0x10, 0xd5,
	0x16, 0xda, 0x91, 0x45, 0x6c, 0xa2, 0x54, 0xf8, 0x1d, 0x68, 0x27, 0x0b, 0x9e, 0x5e, 0x53, 0x75,
	0x21, 0xb5, 0x82, 0x1c, 0x52, 0x07, 0x71, 0x0f, 0x1a, 0xca, 0xb6, 0xda, 0x88, 0x9d, 0x7a, 0x6f,
	0x90, 0x4a, 0x8d, 0x7b, 0xf0, 0x40, 0x99, 0x2a, 0x85, 0xf0, 0x68, 0x4a, 0x8f, 0xc7, 0xf0, 0xe3,
	0xaf, 0xc0, 0xd9, 0xcd, 0xc2, 0xad, 0x1d, 0x61, 0x83, 0xfe, 0x4c, 0xfc, 0xc2, 0x88, 0xef, 0x1c,
	0xe9, 0xf2, 0x1b, 0x21, 0x43, 0x7e, 0x07, 0xc8, 0x94, 0xdf, 0x18, 0x59, 0xf2, 0x7b, 0x89, 0x6c,
	0xdc, 0x00, 0xe3, 0xd9, 0x65, 0x1f, 0x35, 0x24, 0x30, 0x42, 0xcd, 0x6f, 0x6c, 0xf9, 0xb7, 0xe3,
	0xa3, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xca, 0x2a, 0x29, 0x86, 0x08, 0x00, 0x00,
}
